// Editorial Interns Name
Employees
| where role has "Editorial Intern"

Employees
| where name has "Clark Kent"

// Email recieved from ronnie
Email
| where recipient has "clark_kent@valdoriantimes.news"
| where timestamp between (datetime(2024-01-31T00:40:12Z) .. datetime(2024-01-31T16:40:12Z))

// Sonia Gose, IP: 10.10.0.3, Hostname: UL0M-MACHINE

// Role search
Employees
| where name has "Sonia Gose"

// Sus email
Email
| where sender has "newspaper_jobs@gmail.com"
| where subject has "[EXTERNAL] FW: Invitation to Apply: Lead Political Correspondent"

// When link was clicked on
OutboundNetworkEvents
| where src_ip has "10.10.0.3"
| where url has "https://promotionrecruit.com/published/Valdorian_Times_Editorial_Offer_Letter.docx"

// Time file showed up on pc: 2024-01-05T10:24:04Z
// Full path: C:\Users\sogose\Downloads\Valdorian_Times_Editorial_Offer_Letter.docx
// sha256 hash: 60b854332e393a6a2f0015383969c3ac705126a6b7829b762057a3994967a61f
FileCreationEvents
| where hostname has "UL0M-MACHINE"
| where filename has "Valdorian_Times_Editorial_Offer_Letter.docx"

// file writtent to disk hacktivist_manifesto.ps1, Timestamp: 2024-01-05T10:24:32Z
ProcessEvents
| where hostname has "UL0M-MACHINE"
| where process_name has ".ps1"

// schedule Task cmd: schtasks /create /sc hourly /mo 5 /tn "Hacktivist Manifesto" /tr "powershell.exe -ExecutionPolicy Bypass -File C:\ProgramData\hacktivist_manifesto.ps1"
ProcessEvents
| where hostname has "UL0M-MACHINE"
| where process_commandline has "hacktivist_manifesto.ps1"

//
ProcessEvents
| where hostname has "UL0M-MACHINE"
| where process_commandline has "plink.exe"

// commands ran by user
ProcessEvents
| where hostname has "UL0M-MACHINE"
| where parent_process_name has "cmd.exe"

// OTHERS

// Emails sent by: valdorias_best_recruiter@gmail.com
Email
| where sender has "valdorias_best_recruiter@gmail.com"
// Timestamp of email sent to ronnie: 2024-01-10T08:48:16Z
// Domain Name: promotionrecruit.org
| where recipient has "ronnie"

// Ronnie's IP: 10.10.0.19, hostname: A37A-DESKTOP
Employees
| where name has "Ronnie"

// Link in email: https://promotionrecruit.org/share/Editorial_J0b_Openings_2024.docx
OutboundNetworkEvents
| where src_ip has "10.10.0.19"
| where url has "https://promotionrecruit.org/share/Editorial_J0b_Openings_2024.docx"

// File was downloaded, timestamp: 2024-01-10T08:55:17Z
FileCreationEvents
| where hostname has "A37A-DESKTOP"
| where filename has "Editorial_J0b_Openings_2024.docx"

// ps file dropped to Ronnies Machine, timestamp 2024-01-10T08:55:51Z
ProcessEvents
| where hostname has "A37A-DESKTOP"
| where process_name has ".ps1"

ProcessEvents
| where hostname has "A37A-DESKTOP"
| where process_commandline has "plink.exe"

// cmds ran on machine
ProcessEvents
| where hostname has "A37A-DESKTOP"
| where parent_process_name has "cmd.exe"
| where timestamp >= datetime(2024-01-10T08:55:51Z)

// fakestory.docx evidence
OutboundNetworkEvents
| where src_ip has "10.10.0.19"
| where url has "fakestory.docx"

// File Created
FileCreationEvents
| where hostname has "A37A-DESKTOP"
| where filename has "fakestory.docx"

// File was renamed
ProcessEvents
| where hostname has "A37A-DESKTOP"
| where process_commandline has "fakestory.docx"

// Find other actions done by attacker
ProcessEvents
| where timestamp between (datetime(2024-01-21 07:00:00) .. datetime(2024-01-21 12:00:00))
| where hostname == "A37A-DESKTOP"
| order by timestamp asc

// .7z file, and upload
ProcessEvents
| where hostname has "A37A-DESKTOP"
| where timestamp >= datetime(2024-01-31T10:26:20Z)

//Check to see if anyone else had the malware
ProcessEvents
| where process_commandline has "hirejob.com"
